import { ClerkProvider } from "@clerk/nextjs";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import LeftSideBar from "../components/homeContent/LeftSideBar";
import MainContainer from "../components/homeContent/MainContainer";
import RightSideBar from "../components/homeContent/RightSide";
import BottomBar from "../components/homeContent/BottomBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Social media app in next js",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${inter.className} bg-purple-2`}>
          <main className="flex flex-row">
            <LeftSideBar />
            <MainContainer>{children}</MainContainer>
            <RightSideBar />
          </main>
          <BottomBar />
        </body>
      </html>
    </ClerkProvider>
  );
}
